name: Build and Test - r3edge-task-dispatcher

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '**/*.md'

permissions:
  contents: read
  packages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission for Gradle
        run: chmod +x ./gradlew

      - name: Build and run tests
        uses: gradle/gradle-build-action@v3
        with:
          arguments: clean build --info

      - name: Publish test results (JUnit)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: build/test-results/test

      - name: Upload coverage report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports
