name: CI – Build & Publish

on:
  push:
    branches: 
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

permissions:
  contents: read     # checkout + lecture de code
  packages: write    # nécessaire pour read & write packages

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      - name: Build and Test
        run: ./gradlew clean build --no-daemon

      - name: Publish to GitHub Packages
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew publish --no-daemon
        env:
          # votre PAT pour publier
          GPR_USER: ${{ secrets.GPR_USER }}
          GPR_KEY:  ${{ secrets.GPR_KEY }}

